### ISSUE TITLE
Unable to change email address in profile: "Profile can't be blank"

### ISSUE THREAD

**Issue by pfgilbert** [railsbridge/bridge_troll#313] opened 2015-03-17 17:44 UTC
When I try to change the email address in my profile, and fill in my current password, I get: 

1 error prohibited this user from being saved:
Profile can't be blank

Possibly related, when I click on "View Public Profile", I get:

We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

**Comment by tjgrathwell** [comment] 2015-03-17 20:48
Thanks for creating this issue, @pfgilbert - I did some database spelunking and I think I've found the root cause of these problems. I'll try to get a fix out sometime tonight.

**Comment by tjgrathwell** [comment] 2015-03-18 02:07
Alright, your settings page should work again and I've committed a change (f2fd702c166b56b62d40c2de526fcd0b6b12c528) to hopefully ensure this doesn't happen again.

I'm gonna close this issue, but please reopen if the fix didn't work!

**Closed by tjgrathwell** 2015-03-18 02:07 UTC

**Comment by pfgilbert** [comment] 2015-03-18 02:45
Thanks @tjgrathwell -- It works!
