### ISSUE TITLE
drafted emails not received by any recipients

### ISSUE THREAD

**Issue by tremlab** [railsbridge/bridge_troll#629] opened 2019-03-12 19:28 UTC
https://github.com/railsbridge/bridge_troll/issues/284

Possibly reopening the above issue, but -- after various tests I have not once been able to confirm any of my drafted emails has successfully been received by any of the addresses it was sent to.

I (and others) do certainly receive all of the auto-sent emails confirming the event, which is what has me a bit confused. 🤔

drafted from this page:
https://www.bridgetroll.org/events/[id]/emails/new

is it working for others?

many thanks!!!!! ❤️

**Comment by btyy77c** [comment] 2019-08-06 10:18
I just tried to send myself a test email. I wanted to check and make sure it worked before sending an email to volunteers.  It appears to be broken for me as well.

**Comment by michaelglass** [comment] 2019-08-08 13:29
The last email I received from Bridgetroll was in June. BridgeTroll uses SendGrid. @tremlab let's pair on it whenever you get a chance.

**Comment by btyy77c** [comment] 2019-08-12 13:09
Updated info:  My yahoo account will not send emails.  A different gmail account will send emails.

**Comment by michaelglass** [comment] 2019-08-12 13:36
won't receive emails?

**Comment by btyy77c** [comment] 2019-08-12 15:02
In production, I attempted to send emails for this event:
https://www.bridgetroll.org/events/472

I attempted to send 1 test email to a "test volunteer" I setup . The email was never received by the "test volunteer". I posted the comment from 6 days ago, letting you know emails were not working in production. 

Another event organizer sent a test email to all volunteers.  Their test email was successfully received.

I sent another 3 emails yesterday to, thinking the emails were working again.  0 of the 3 emails I sent were received.

I noticed the emails were sending from our personal account email address. My email is a yahoo email address. The other event organizer has a gmail address. 

I tried sending the 3 emails again, this time using a gmail account.  The emails were confirmed to be received.

**Comment by michaelglass** [comment] 2019-08-12 15:07
Got it!

I think this clarifies what's wrong. Bridgetroll isn't actually sending it _from_ your account, but from its sendgrid account, masquerading as your account. It wouldn't surprise me if that masquerading is having some emails dropped.

**Comment by btyy77c** [comment] 2019-08-12 15:19
Preferably, it would be nice to be able to view the student/volunteer email addresses and send emails outside of the RailsBridge system.

It looks like the ability to view emails was removed previously (https://github.com/railsbridge/bridge_troll/issues/437) so I'm not sure that's an option :( 

It's very difficult to plan an event when communication is so difficult.  

There is no confirmation that emails are not sending, which means some organizers may not be aware their emails are failing.... and if for some reason I was unable to create a gmail account, I would have no way to contact students/volunteers.

**Comment by michaelglass** [comment] 2019-08-12 15:28
I'm sorry you've been so frustrated with that functionality. There are a lot of advantages to using bridge troll, but it's also an open source project run by volunteers, so life stuff often takes priority over fixing bugs, especially those that are hard to reproduce.

@tremlab and I will try to get a fix out tonight. We'll see how much success we have!

**Comment by tremlab** [comment] 2019-08-12 16:22
Confirming my (failing) emails are also coming from a yahoo login. Thanks for catching that detail!

**Comment by michaelglass** [comment] 2019-08-13 13:40
@tremlab / @btyy77c pushed a fix. Can y'all try again?

**Comment by michaelglass** [comment] 2019-08-13 16:25
fixed! yay

**Closed by michaelglass** 2019-08-13 16:25 UTC

**Comment by tremlab** [comment] 2019-08-13 18:02
with the fix deployed, I was able to send emails to my volunteers, even from my yahoo login.  

This is going to make it so much easier to organize the next event! Thanks you so much for the help here.  ❤️
